on:
  push:
    branches: [main]
    paths:
    - 'src/**'
    - '.github/workflows/maven.yml'

jobs:
  lint-workflow:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  construct-job:
    runs-on: ubuntu-latest
    needs:
      - lint-workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MySQL
        run: sudo service mysql start

      - name: Create Database from script
        run: mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} < "source infra/springboot_person.sql"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          architecture: 'x64'

      - name: Cache SonarScanner packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build JAR and analyze SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=myKey_projectKey1321343_Sprint6

      # Process en charge du restart
      - name: Changing artifcat
        uses: actions/upload-artifact@v4
        with:
          name: package.jar
          path: target/*.jar
          retention-days: 1